chain_width = 60
edition = "2021"
empty_item_single_line = true
fn_single_line = false
hard_tabs = true
max_width = 120
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
unstable_features = true
use_small_heuristics = "Max"
use_try_shorthand = true
