[package]
name = "tf"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.35"
clap = { version = "4.5.3", features = ["derive"] }
colored = "2.1.0"
filetime = "0.2.23"
mime_guess = "2.0.4"
rayon = "1.10.0"
thiserror = "1.0.58"
walkdir = "2.5.0"
